# Frigate configuration file for Raspberry Pi 5 with Hailo-8 AI Hat

mqtt:
  enabled: true
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

detectors:
  hailo:
    type: hailo8l
    device: PCIe
    device_id: 0

model:
  path: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ModelZoo/Compiled/v2.14.0/hailo8/yolov8n.hef

# Cameras configuration - at least one camera is required
cameras:
  # Arducam 1080P Day & Night Vision USB Camera - 2MP with IR LEDs
  arducam:
    ffmpeg:
      inputs:
        - path: /dev/video0
          input_args: -f v4l2 -input_format mjpeg -video_size 1920x1080 -framerate 10 -fflags nobuffer -avoid_negative_ts make_zero -threads 2 -thread_type slice
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 7

  # Logitech Webcam C925e USB camera - CPU Optimized (COMMENTED OUT)
  # webcam:
  #   ffmpeg:
  #     inputs:
  #       - path: /dev/video0
  #         input_args: -f v4l2 -input_format mjpeg -video_size 1280x720 -framerate 15 -fflags nobuffer -avoid_negative_ts make_zero
  #         roles:
  #           - detect
  #           - record
  #   detect:
  #     width: 1280
  #     height: 720
  #     # width: 640
  #     # height: 480
  #     fps: 5
  #   record:
  #     enabled: true
  #     retain:
  #       days: 7
  #       mode: motion
  #   snapshots:
  #     enabled: true
  #     timestamp: true
  #     bounding_box: true
  #     retain:
  #       default: 7

# Global settings
record:
  enabled: true
  retain:
    days: 7
    mode: motion

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7

# Motion detection settings
motion:
  threshold: 25
  contour_area: 100
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50

# Object detection settings
objects:
  track:
    - person
    - hat
    - tie
    - backpack
    - suitcase
    - handbag
    - eye glasses
    - shoe
    - cell phone
    - mouse

  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
    backpack:
      min_area: 1000
      max_area: 20000
      min_score: 0.4
    suitcase:
      min_area: 1500
      max_area: 25000
      min_score: 0.4
    handbag:
      min_area: 1000
      max_area: 20000
      min_score: 0.4
    hat:
      min_area: 500
      max_area: 5000
      min_score: 0.3
    tie:
      min_area: 300
      max_area: 3000
      min_score: 0.3
    eye glasses:
      min_area: 200
      max_area: 2000
      min_score: 0.3
    shoe:
      min_area: 200
      max_area: 2000
      min_score: 0.3
    cell phone:
      min_area: 500
      max_area: 3000
      min_score: 0.4
    mouse:
      min_area: 300
      max_area: 2000
      min_score: 0.3


detect:
  enabled: true
version: 0.16-0
