services:
    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto
        restart: unless-stopped
        ports:
            - "1883:1883" # MQTT protocol
            - "9001:9001" # WebSocket (optional)
        volumes:
            - ./config:/mosquitto/config
            - ./data:/mosquitto/data
            - ./log:/mosquitto/log
